// Bulk Slovenian -> English translation script for MojAvto page controllers
const fs = require('fs');
const path = require('path');

const ROOT = __dirname;
const files = [
  'src/pages/oglasi.js',
  'src/pages/home.js',
  'src/pages/listing.js',
  'src/pages/create-listing.js',
  'src/pages/advanced-search.js',
  'src/pages/admin.js',
  'src/pages/booking.js',
  'src/pages/business-profile.js',
  'src/pages/compare.js',
  'src/pages/dashboard.js',
  'src/pages/evaluate.js',
  'src/pages/map.js',
  'src/pages/parts.js',
  'src/pages/profile.js',
  'src/pages/service-entry.js',
  'src/pages/tire-product.js',
  'src/pages/tire-search.js',
  'src/pages/b2b-dashboard.js',
  'src/pages/b2b-inventory.js',
  'src/pages/b2b-leads.js',
  'src/pages/b2b-profile-editor.js',
  'src/pages/b2b-reservations.js',
  'src/pages/b2b-services.js',
  'src/pages/b2b-tire-hotel.js',
  'src/pages/b2b-workshop.js',
];

// Ordered list of literal replacements (longest/specific first to avoid sub-conflicts).
// Each entry is [search, replace]. Treated as plain literal multi-occurrence replace.
const replacements = [
  // Phrases (longest first)
  ['Lahko primerjate največ', 'You can compare a maximum of'],
  ['vozila naenkrat.', 'vehicles at once.'],
  ['Prišlo je do napake pri posodabljanju priljubljenih.', 'An error occurred while updating favorites.'],
  ['Prijavite se, da shranite oglas v svojo garažo všečkanih vozil.', 'Sign in to save this listing to your favorites garage.'],
  ['Prijavite se, da shranite ta oglas med všečkane.', 'Sign in to save this listing to your favorites.'],
  ['Prijavite se, da dodate vozilo v primerjavo.', 'Sign in to add a vehicle to comparison.'],
  ['Trenutno ni izpostavljenih oglasov v tej kategoriji.', 'There are no featured listings in this category at the moment.'],
  ['Verificirana servisna zgodovina', 'Verified service history'],
  ['Servisna zgodovina', 'Service History'],
  ['Mali servis', 'Minor Service'],
  ['Veliki servis', 'Major Service'],
  ['Popravilo', 'Repair'],
  ['Pnevmatike', 'Tires'],
  ['Drugo', 'Other'],
  ['Ocena cene ni na voljo', 'Price rating not available'],
  ['Visoka zanesljivost', 'High confidence'],
  ['Srednja zanesljivost', 'Medium confidence'],
  ['Odlična vrednost', 'Excellent value'],
  ['Dobra vrednost', 'Good value'],
  ['Poštena cena', 'Fair price'],
  ['Nad povprečjem', 'Above average'],
  ['Predrago', 'Overpriced'],
  ['Odlična cena', 'Great price'],
  ['Povprečna cena', 'Average price'],
  ['Redka oprema', 'Rare equipment'],
  ['Shrani med všečkane', 'Save to favorites'],
  ['Dodaj v primerjavo', 'Add to compare'],
  ['Primerjaj vozila', 'Compare Vehicles'],
  ['Primerjaj', 'Compare'],
  ['Všečkaj', 'Like'],
  ['Lahko primerjate največ 3 vozila naenkrat.', 'You can compare a maximum of 3 vehicles at once.'],
  ['Zasebni prodajalec', 'Private Seller'],
  ['Pooblaščeni trgovec', 'Authorized Dealer'],
  ['Avtohiša', 'Dealership'],
  ['Delovni čas', 'Business Hours'],
  ['Opomnik prodajalca', 'Seller Note'],
  ['Pošlji sporočilo', 'Send Message'],
  ['Oglas ni bil najden.', 'Listing not found.'],
  ['Manjkajoč ID oglasa.', 'Missing listing ID.'],
  ['Oglas ne obstaja.', 'Listing does not exist.'],
  ['Promoviran oglas', 'Promoted listing'],
  ['Sponzoriran oglas', 'Sponsored listing'],
  ['Zunanjost', 'Exterior'],
  ['Notranjost in udobje', 'Interior & Comfort'],
  ['Notranjost', 'Interior'],
  ['ogledov', 'views'],
  ['VIN preverjeno', 'VIN verified'],
  ['Opis vozila', 'Vehicle Description'],
  ['Cena je pogajalska', 'Price is negotiable'],
  ['Možnost leasinga', 'Financing available'],
  ['Preveri možnost leasinga / hitrega kredita', 'Check financing / quick loan options'],
  ['Leasing / hitri kredit', 'Financing / Quick Loan'],
  ['Podobni oglasi', 'Similar Listings'],
  ['Nalagam podobne oglase...', 'Loading similar listings...'],
  ['Ni podobnih oglasov.', 'No similar listings.'],
  ['Nesreče', 'Accidents'],
  ['Ni zabeleženih', 'None recorded'],
  ['zabeleženih', 'recorded'],
  ['zabeležena', 'recorded'],
  ['hujša', 'major'],
  ['manjša', 'minor'],
  ['Odpoklici', 'Recalls'],
  ['Odprti odpoklici — preverite pri servisu', 'Open recalls — check with service center'],
  ['Ni odprtih odpoklicov', 'No open recalls'],
  ['Znamka / Model', 'Make / Model'],
  ['Leto izdelave', 'Year of manufacture'],
  ['Država izvora', 'Country of origin'],
  ['Prejšnji lastniki', 'Previous owners'],
  ['Nekateri podatki so bili ročno urejeni s strani prodajalca po verifikaciji VIN.', 'Some data was manually edited by the seller after VIN verification.'],
  ['Podatki pridobljeni iz uradnih registrov in baz vozilnih zgodovin.', 'Data obtained from official registries and vehicle history databases.'],
  ['Tehnični podatki', 'Technical Specifications'],
  ['Vse specifikacije in podrobnosti', 'All specifications and details'],
  ['Oprema in funkcije', 'Equipment & Features'],
  ['Oprema (varnost, razsvetljava, udobje, multimedija)', 'Equipment (safety, lighting, comfort, multimedia)'],
  ['Prva registracija', 'First Registration'],
  ['Vrsta vozila', 'Vehicle Type'],
  ['Prevoženi km', 'Mileage'],
  ['Vrsta goriva', 'Fuel Type'],
  ['Menjalnik', 'Transmission'],
  ['Prostornina', 'Engine Displacement'],
  ['Domet WLTP', 'WLTP Range'],
  ['Domet', 'Range'],
  ['Poraba (kombinirana)', 'Fuel Economy (combined)'],
  ['Poraba (mestna)', 'Fuel Economy (city)'],
  ['Poraba (izvenmestna)', 'Fuel Economy (highway)'],
  ['Poraba', 'Fuel Economy'],
  ['Stanje', 'Condition'],
  ['Pogon', 'Drivetrain'],
  ['Št. lastnikov', 'Number of owners'],
  ['Barva', 'Color'],
  ['Vrata', 'Doors'],
  ['Sedeži', 'Seats'],
  ['CO₂ emisije', 'CO₂ emissions'],
  ['Emisijski razred', 'Emission class'],
  ['Tip hibrida', 'Hybrid Type'],
  ['Kapaciteta baterije', 'Battery Capacity'],
  ['Vlečna masa', 'Towing capacity'],
  ['Registrirana do', 'Registered until'],
  ['Moč', 'Power'],
  ['vrat', 'doors'],
  ['Glavna slika', 'Main image'],
  ['Slika', 'Image'],
  ['Ni fotografij', 'No photos'],
  ['Ni slike', 'No image'],
  ['Izpostavljeno', 'Featured'],
  ['Nazaj na domov', 'Back to home'],
  ['Nazaj na seznam', 'Back to list'],
  ['Domov', 'Home'],
  ['Avto', 'Car'],
  ['Moto', 'Motorcycle'],
  ['Gospodarska vozila', 'Commercial Vehicles'],
  ['Gospodarska', 'Commercial'],
  ['Avtomobili', 'Cars'],
  ['Motorji', 'Motorcycles'],
  ['Mehanizacija', 'Machinery'],
  ['Prosti čas', 'Leisure'],
  ['Deli', 'Parts'],
  ['Oglasi', 'Listings'],
  ['Vse znamke', 'All Makes'],
  ['Vsi modeli', 'All Models'],
  ['Prejšnja slika', 'Previous image'],
  ['Naslednja slika', 'Next image'],
  ['Kontakt', 'Contact'],
  ['Zapri', 'Close'],
  ['Prijavite se', 'Sign in'],
  // Locale strings used in formatters
  ["new Intl.NumberFormat('sl-SI', { style: 'currency', currency: 'EUR', maximumFractionDigits: 0 })",
   "new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 0 })"],
  ["new Intl.NumberFormat('sl-SI')", "new Intl.NumberFormat('en-US')"],
  ["toLocaleDateString('sl-SI'", "toLocaleDateString('en-US'"],
  ['€', '$'],
  ['EUR', 'USD'],
  // Unit suffixes
  [" km'", " mi'"], // for ' km' literal in templates (be cautious — only matches that exact pattern)
  [' kW', ' HP'],
  [" l/100 km'", " MPG'"],
  ['Ni+slike', 'No+image'],
];

let totalChanges = 0;
for (const rel of files) {
  const fp = path.join(ROOT, rel);
  if (!fs.existsSync(fp)) { console.log('SKIP missing', rel); continue; }
  let src = fs.readFileSync(fp, 'utf8');
  const before = src;
  for (const [s, r] of replacements) {
    if (s === r) continue;
    if (src.indexOf(s) !== -1) {
      src = src.split(s).join(r);
    }
  }
  if (src !== before) {
    fs.writeFileSync(fp, src, 'utf8');
    totalChanges++;
    console.log('UPDATED', rel);
  } else {
    console.log('no-change', rel);
  }
}
console.log('Files changed:', totalChanges);
